- id: zizmor
  name: zizmor
  description: "Find security issues in GitHub Actions CI/CD setups"
  language: python
  types: [yaml]
  require_serial: true
  entry: zizmor
  args:
    - "--no-progress" # https://github.com/zizmorcore/zizmor/issues/582
