repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: d19233b89771be2d89273f163f5edc5a39bbc34a  # frozen: v0.11.12
    hooks:
      - id: ruff
        args: [--fix]
      - id: ruff-format

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: cef0300fd0fc4d2a87a85fa2093c6b283ea36f4b  # frozen: v5.0.0
    hooks:
      - id: check-added-large-files
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: check-toml
      - id: check-yaml
      - id: debug-statements
      - id: end-of-file-fixer
      - id: forbid-submodules
      - id: trailing-whitespace

  - repo: https://github.com/python-jsonschema/check-jsonschema
    rev: 9932a7df36a32ef5e79dfd5df26ad89ca15bfa61  # frozen: 0.30.0
    hooks:
      - id: check-github-workflows

  - repo: https://github.com/zizmorcore/zizmor-pre-commit
    rev: 451b56af716f9f0d0c2b816503a3fd0cf8b036fa  # frozen: v1.29.0
    hooks:
      - id: zizmor

  - repo: https://github.com/abravalheri/validate-pyproject
    rev: f45606bad11ad90ddac1212fa83ebe2a4d724351  # frozen: v0.23
    hooks:
      - id: validate-pyproject

  - repo: meta
    hooks:
      - id: check-hooks-apply
      - id: check-useless-excludes
